 export default [ 
                    "Manufacturing",
                    "Production",
                    "Retail",
                    "Industry",
                    "Food Industry",
                    "Construction",
                    "Trade",
                    "Agriculture",
                    "Education",
                    "Marketing",
                    "Finance",
                    "Technology",
                    "Mining",
                    "Market Research",
                    "Transport",
                    "Food Service",
                    "Insurance",
                    "Hospitality Industry",
                    "Real Estate",
                    "Health Care Coverage and Access",
                    "Advertising",
                    "Goods",
                    "Distrubution",
                    "Telecommunication",
                    "Public Administration",
                    "Economics",
                    "Computer and Information Technology",
                    "Tertiary Sector of the Economy",
                    "Biotechnology",
                    "Sales",
                    "Software",
                    "Energy",
                    "Science",
                    "Management Consulting",
                    "Management consulting",
                    "Entertainment",
                    "Rail Transport",
                    "Fashion",
                    "Law",
                    "Design",
                    "Investment",
                    "Renewable Energy",
                    "Publishing",
                    "Accounting",
                    "Media"
                ]
            